### ISSUE TITLE
derivative (L) matrix should have a square basis

### ISSUE THREAD

**Issue by jjstickel** [mdpetters/RegularizationTools.jl#10]
It seems to me that the derivative `L` matrix should be square (mxm where `m` is the number of columns of `A`) for order 0 (i.e., square identity matrix) and decreasing rows for higher orders, rather than the shape of `A`. At least, that is what is needed for my data-smoothing application. I have made the necessary changes here:

https://github.com/jjstickel/RegularizationTools.jl/commit/604f359cc05833fee585456f3861b96b7519138d

Does this seem reasonable? Or are there cases when `L` should correspond to both dimensions of `A`? All the existing tests pass, but from what I can tell, they all use a square `A`. I'll make a PR later after I have worked out additional code I might want to add.

**Comment by mdpetters** [comment]
Thanks for the comment. After some testing with a non-square system I agree  that ```L``` matrix should be square. In fact, the way it is implemented in the current version,  ```L'L``` is missing  terms in the last rows/columns, which leads to a corresponding lack or regularization at the edge of the domain. The changes mentioned above fix this, and thus also improve the package. A PR would be very welcome.

**Comment by jjstickel** [comment]
Great, thanks for looking at this. I'll submit a PR in the next few days. Still working on some other concepts that may go in this PR or in a second one at a later time.
